name: ESP-IDF Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with "v"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.2.0 # Specify the Node.js version
          check-latest: true   # Ensures the latest patch of the specified version is used

      # Install dependencies and build frontend
      - name: Install and Build Frontend
        working-directory: front
        run: |
          npm install
          npm run build
          
      # Copy web app build to ESP-IDF components for embedding
      - name: Prepare Web App for Embedding
        run: |
          # Copy built web app to components/web_server/static
          cp -r front/build/* components/web_server/static/
          
          # Also copy to a separate artifact directory
          mkdir -p artifacts/webapp
          cp -r front/build/* artifacts/webapp/
  
      # Build with ESP-IDF
      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2.3 # Specify the ESP-IDF version
          target: esp32s3         # Specify the ESP-IDF target
          path: './'              # Set the project path (current directory)

      # Prepare firmware artifacts
      - name: Prepare Firmware Artifacts
        run: |
          mkdir -p artifacts/firmware
          
          # Copy main firmware binary
          cp build/*.bin artifacts/firmware/ 2>/dev/null || echo "No .bin files found"
          
          # Copy partition table and other important files
          cp build/partition_table/partition-table.bin artifacts/firmware/ 2>/dev/null || echo "No partition table found"
          cp build/bootloader/bootloader.bin artifacts/firmware/ 2>/dev/null || echo "No bootloader found"
          
          # Create STM32 firmware binary for SPIFFS upload
          mkdir -p artifacts/stm32
          cp spiffs/digitaldash-firmware-gen2-stm32u5g.bin artifacts/stm32/ 2>/dev/null || echo "No STM32 firmware found"
          
          # List all created artifacts
          echo "Created artifacts:"
          find artifacts -type f -name "*.bin" -o -name "*.html" -o -name "*.js" -o -name "*.css" | head -20

      # Extract changelog for release notes
      - name: Extract Latest Changelog Entry
        run: |
          if [ -f CHANGELOG.md ]; then
            awk '/^## /{if (p) exit; p=1; next} p' CHANGELOG.md > latest_changelog.md
            echo "Extracted release notes:"
            cat latest_changelog.md
          else
            echo "No CHANGELOG.md found, creating default release notes"
            echo "## Release $(echo $GITHUB_REF | sed 's/refs\/tags\///')" > latest_changelog.md
            echo "- ESP32-S3 firmware build" >> latest_changelog.md
            echo "- Web application build" >> latest_changelog.md
            echo "- STM32 firmware for Digital Dash" >> latest_changelog.md
          fi

      # Create a release and upload artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/firmware/*.bin
            artifacts/stm32/*.bin
            artifacts/webapp/**
          body_path: latest_changelog.md
          name: "Digital Dash Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload build artifacts for workflow download
      - name: Upload ESP32 Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware-${{ github.ref_name }}
          path: artifacts/firmware/
          retention-days: 30

      - name: Upload STM32 Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stm32-firmware-${{ github.ref_name }}
          path: artifacts/stm32/
          retention-days: 30

      - name: Upload Web App Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp-${{ github.ref_name }}
          path: artifacts/webapp/
          retention-days: 30
